# Generated by Django 2.0.6 on 2018-10-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181009_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='image',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_image'),
        ),
    ]
