# Generated by Django 2.0.6 on 2018-10-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181009_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='category_image'),
        ),
    ]
