# Generated by Django 2.0.6 on 2018-10-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20181009_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
