# Generated by Django 2.0.6 on 2018-10-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20181009_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='category_image'),
        ),
    ]
