# Generated by Django 2.0.6 on 2018-10-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20181009_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='user_image/user.ico', null=True, upload_to='category_image'),
        ),
    ]
