# Generated by Django 2.0.6 on 2018-10-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20181009_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='college',
        ),
        migrations.AddField(
            model_name='product',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.College'),
        ),
    ]
