# Generated by Django 2.0.6 on 2018-10-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_auto_20181022_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.College')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.BooleanField(default=False),
        ),
    ]
