# Generated by Django 2.0.6 on 2018-10-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20181026_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
