# Generated by Django 2.0.6 on 2018-10-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20181027_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='category_image/default-category.png', null=True, upload_to='product_image'),
        ),
    ]
