# Generated by Django 2.0.6 on 2018-10-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20181027_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='no_of_days',
            new_name='day_of_return',
        ),
    ]
