# Generated by Django 2.0.6 on 2018-10-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20181027_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='day_of_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
