# Generated by Django 2.2.10 on 2020-05-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20181027_1906'),
        ('product', '0004_wisher'),
    ]

    operations = [
    ]
