# Generated by Django 2.2.10 on 2020-05-18 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_merge_20200518_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descripton',
        ),
        migrations.RemoveField(
            model_name='product',
            name='no_of_days',
        ),
        migrations.AddField(
            model_name='product',
            name='day_of_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='category_image/default-category.png', null=True, upload_to='product_image'),
        ),
    ]
